### ISSUE TITLE
Script no longer works on Raspberry Pi

### ISSUE THREAD

**Issue by danturner1981** [neutrinolabs/pulseaudio-module-xrdp#109] opened 2024-01-25 12:07 UTC
Trying to run the apt_wrapper.sh script on the latest Raspbian Bookworm and getting this in my debootstrap.log file:

: Target architecture can be executed
I: Retrieving InRelease
I: Checking Release signature
E: Release signed by unknown key (key id 9165938D90FDDD2E)
   The specified keyring /usr/share/keyrings/debian-archive-keyring.gpg may be incorrect or out of date.
   You can find the latest Debian release key at https://ftp-master.debian.org/keys.html

It would appear that there is no /etc/apt/trusted.gpg file anymore as apt-key is now deprecated and all keys now live in /etc/apt/trusted.gpg.d. Any idea how the script could be modified to make this work again? I really, really need this module but am not experienced enough to figure it out!

**Comment by matt335672** [comment] 2024-01-25 16:13
@danturner1981 - I'll get this when I can. We're all rather busy at the moment working on GFX support. I'm sure there will be a simple fix.

**Comment by danturner1981** [comment] 2024-01-25 16:21
Thank you! It would be most appreciated

**Comment by matt335672** [comment] 2024-01-26 11:40
@danturner1981 - are you running pulseaudio on your system?

My understanding (which could be wrong) is that the PI bookworm distro uses pipewire by default. We have a separate module for that:-

https://github.com/neutrinolabs/pipewire-module-xrdp

I'll need to build a VM to reproduce your problem which will take a while on my ageing system. It's possible if you're using the v0.7 tarball your problem may be fixed in the latest devel version of the scripts - ther have been changes in this area. See https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/Build-on-Debian-or-Ubuntu

**Comment by danturner1981** [comment] 2024-01-26 15:29
Thanks for the update. I am using pulseaudio: bookworm does use pipewire by default but raspi-config allows one to revert to pulse instead. I need PA due to the use of Apache guacamole, which uses PA for audio.

I have been using the script you mention; it's this command that's not working:

./install_pulseaudio_sources_apt_wrapper.sh \
    --mirror=http://raspbian.raspberrypi.org/raspbian \
   --keyring=/etc/apt/trusted.gpg

This because --keyring=/etc/apt/trusted.gpg no longer works due to apt-key now being deprecated, and hence there no longer being a trusted.gpg file in existence.

**Comment by matt335672** [comment] 2024-01-26 16:05
Ah - I see the problem now.

I'm out of time today, but I'll look when I can.

What do you get for this command?

```
ls /etc/apt/trusted.gpg.d/
```

I suspect one of these files needs to be specified instead, but I don't have a PI handy to look. You could also try completely omitting the --keyring switch.

**Comment by danturner1981** [comment] 2024-01-26 16:07
PUBLIC / CYHOEDDUS

Hi Matt,

I get this:


debian-archive-bookworm-automatic.asc

debian-archive-bookworm-security-automatic.asc

debian-archive-bookworm-stable.asc

debian-archive-bullseye-automatic.asc

debian-archive-bullseye-security-automatic.asc

debian-archive-bullseye-stable.asc

debian-archive-buster-automatic.asc

debian-archive-buster-security-automatic.asc

debian-archive-buster-stable.asc

raspberrypi-archive-stable.gpg


Kind Regards,

Dan

From: matt335672 ***@***.***>
Date: Friday, 26 January 2024 at 16:06
To: neutrinolabs/pulseaudio-module-xrdp ***@***.***>
Cc: Dan Turner ***@***.***>, Mention ***@***.***>
Subject: Re: [neutrinolabs/pulseaudio-module-xrdp] Script no longer works on Raspberry Pi (Issue #109)
CAUTION: This email originated from outside of USW. Only click on links or open attachments if you recognise the sender and are expecting them. If you have concerns about this email then please forward it to ***@***.***

RHYBUDD: Mae'r e-bost hwn yn tarddu o'r tu allan i PDC. Peidiwch â chlicio dolenni nac agor atodiadau oni bai eich bod yn adnabod yr anfonwr ac yn eu disgwyl. Os oes gennych bryderon am yr e-bost hwn yna anfonwch e ymlaen at ***@***.***

Ah - I see the problem now.

I'm out of time today, but I'll look when I can.

What do you get for this command?

ls /etc/apt/trusted.gpg.d/

I suspect one of these files needs to be specified instead, but I don't have a PI handy to look. You could also try completely omitting the --keyring switch.

**Comment by danturner1981** [comment] 2024-01-27 00:11
I should also mention that omitting the --keyring gets me through debootstrap but fails on the next process (schroot?)

**Comment by matt335672** [comment] 2024-01-27 17:08
@danturner1981 -  I can try this out on "Raspberry PI desktop" for x86_64, but that's not based on Debian 12. So I'll need more help from you to sort this out.

Can you provide logs for what happens when you omit the `--keyring` switch?

Thanks.

**Comment by matt335672** [comment] 2024-01-27 17:20
Can you also tell me what's in the directory `/etc/apt/sources.list.d` on the PI? If there aren't many files, their contents would be useful too.

**Comment by danturner1981** [comment] 2024-01-29 14:31
If I omit the --keyring switch, I get this:

: Target architecture can be executed
I: Retrieving InRelease
I: Checking Release signature
E: Release signed by unknown key (key id 9165938D90FDDD2E)
   The specified keyring /usr/share/keyrings/debian-archive-keyring.gpg may be incorrect or out of date.
   You can find the latest Debian release key at https://ftp-master.debian.org/keys.html

The contents of /etc/apt/sources.list.d are as follows: bullseye.list  raspi.list

Hope that is of some help.

**Comment by matt335672** [comment] 2024-01-29 14:37
Thanks.

Can you tell me what you get for `cat /etc/apt/sources.list.d/bullseye.list raspi.list` ?

Also, (a long shot) try the `./install_pulseaudio_sources_apt_wrapper.sh` without any switches.

Sorry about the flailing about, but without hardware it's a challenge to work out exactly what's going on.

**Comment by danturner1981** [comment] 2024-01-29 15:42
cat /etc/apt/sources.list.d/bullseye.list raspi.list gives me this:

```
deb http://deb.debian.org/debian/ bullseye main
deb http://archive.raspberrypi.com/debian/ bookworm main
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspberrypi.com/debian/ bookworm main
```
Running the switch switchless gets me through the deboostrap process but fails on schroot. Here's the log file for that:

```
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 82B129927FA3303E
Get:7 http://deb.debian.org/debian bookworm/contrib arm64 Packages [45.6 kB]
Get:8 http://deb.debian.org/debian bookworm/contrib Translation-en [48.7 kB]
Get:9 http://deb.debian.org/debian bookworm/non-free arm64 Packages [75.4 kB]
Get:10 http://deb.debian.org/debian bookworm/non-free Translation-en [66.8 kB]
Get:11 http://deb.debian.org/debian bookworm/non-free-firmware arm64 Packages [5824 B]
Get:12 http://deb.debian.org/debian bookworm/non-free-firmware Translation-en [20.8 kB]
Get:13 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [132 kB]
Get:14 http://deb.debian.org/debian-security bookworm-security/main Translation-en [80.0 kB]
Get:15 http://deb.debian.org/debian-security bookworm-security/contrib Translation-en [372 B]
Get:16 http://deb.debian.org/debian-security bookworm-security/non-free-firmware Translation-en [472 B]
Get:17 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [12.5 kB]
Get:18 http://deb.debian.org/debian bookworm-updates/main Translation-en [13.8 kB]
Get:19 http://deb.debian.org/debian bullseye/main arm64 Packages [7951 kB]
Get:20 http://deb.debian.org/debian bullseye/main Translation-en [6236 kB]
Reading package lists...
W: GPG error: http://archive.raspberrypi.com/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 82B129927FA3303E
E: The repository 'http://archive.raspberrypi.com/debian bookworm InRelease' is not signed.
Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  lsb-release sudo
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1833 kB of archives.
After this operation, 6528 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 sudo arm64 1.9.13p3-1+deb12u1 [1826 kB]
Get:2 http://deb.debian.org/debian bookworm/main arm64 lsb-release all 12.0-1 [6416 B]
Fetched 1833 kB in 2s (1088 kB/s)
Selecting previously unselected package sudo.
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%^M(Reading database ... 30%^M(Reading database >
Preparing to unpack .../sudo_1.9.13p3-1+deb12u1_arm64.deb ...
Unpacking sudo (1.9.13p3-1+deb12u1) ...
Selecting previously unselected package lsb-release.
Preparing to unpack .../lsb-release_12.0-1_all.deb ...
Unpacking lsb-release (12.0-1) ...
Setting up sudo (1.9.13p3-1+deb12u1) ...
Running in chroot, ignoring request.
Setting up lsb-release (12.0-1) ...
Processing triggers for libc-bin (2.36-9+deb12u3) ...
Building for : Debian-12 (bookworm)
- Adding source repositories
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Get:3 http://archive.raspberrypi.com/debian bookworm InRelease [23.6 kB]
Hit:4 http://deb.debian.org/debian-security bookworm-security InRelease
Get:5 http://deb.debian.org/debian bookworm/contrib Sources [51.3 kB]
Get:6 http://deb.debian.org/debian bookworm/non-free-firmware Sources [6168 B]
Get:7 http://deb.debian.org/debian bookworm/non-free Sources [77.9 kB]
Get:8 http://deb.debian.org/debian bookworm/main Sources [9488 kB]
Err:3 http://archive.raspberrypi.com/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 82B129927FA3303E
Get:9 http://deb.debian.org/debian bookworm-updates/main Sources [17.4 kB]
Get:10 http://deb.debian.org/debian-security bookworm-security/non-free-firmware Sources [796 B]
Get:11 http://deb.debian.org/debian-security bookworm-security/contrib Sources [852 B]
Get:12 http://deb.debian.org/debian-security bookworm-security/main Sources [73.0 kB]
Reading package lists...
W: GPG error: http://archive.raspberrypi.com/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 82B129927FA3303E
E: The repository 'http://archive.raspberrypi.com/debian bookworm InRelease' is not signed.
```

**Comment by matt335672** [comment] 2024-01-29 16:20
That file doesn't look right :-

```
$ cat /etc/apt/sources.list.d/bullseye.list raspi.list
deb http://deb.debian.org/debian/ bullseye main
deb http://archive.raspberrypi.com/debian/ bookworm main
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspberrypi.com/debian/ bookworm main
```

You shouldn't have a mix of Debian bullseye and Raspberry PI repositories in there.

I'm not sure what I can do to advise you to sort this out. I don't want to advise you to do something which could wreck a currently working system.

**Comment by danturner1981** [comment] 2024-01-29 22:51
PUBLIC / CYHOEDDUS

Fair enough. Thanks for taking the time to check it out

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by matt335672** [comment] 2024-01-30 10:01
I'll leave this open for now.

If you get a clean install of bookworm, or I get suitable hardware I'll be happy to take another look at this.

**Comment by russ-g53** [comment] 2024-02-13 19:42
Have the same problem as original poster.  Raspberry pi 5 clean install.  Same issue as noted

""I have been using the script you mention; it's this command that's not working:

./install_pulseaudio_sources_apt_wrapper.sh
--mirror=http://raspbian.raspberrypi.org/raspbian
--keyring=/etc/apt/trusted.gpg

This because --keyring=/etc/apt/trusted.gpg no longer works due to apt-key now being deprecated, and hence there no longer being a trusted.gpg file in existence.""


here is the output of my raspi.list
deb http://archive.raspberrypi.com/debian/ bookworm main
#Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspberrypi.com/debian/ bookworm main

**Closed as completed** 2024-09-09 10:50 UTC
